version: "3.8"

services:
  mongodb:
    image: mongo:7.0
    container_name: weather-mongodb
    restart: unless-stopped
    ports:
      - "27018:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USERNAME:-admin}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD:-password}
      MONGO_INITDB_DATABASE: ${MONGO_DBNAME:-weather_db}
    volumes:
      - ./infra/data/mongo:/data/db
    networks:
      - gdash-network

  rabbitmq:
    image: rabbitmq:3-management
    container_name: weather-rabbitmq
    restart: unless-stopped
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER:-guest}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASSWORD:-guest}
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - gdash-network

  backend:
    build:
      context: ./backend/api
      dockerfile: Dockerfile
    container_name: weather-backend
    restart: unless-stopped
    env_file:
      - .env
    environment:
      MONGO_URL: ${MONGO_URL}
      RABBITMQ_URL: ${RABBITMQ_URL}
      NODE_ENV: development
    depends_on:
      - mongodb
      - rabbitmq
    ports:
      - "3000:3000"
    networks:
      - gdash-network

  worker:
    build: ./worker-go
    container_name: weather-worker
    depends_on:
      rabbitmq:
        condition: service_healthy
      backend:
        condition: service_started
    environment:
      RABBITMQ_URL: ${RABBITMQ_URL}
      BACKEND_URL: ${BACKEND_URL}
    networks:
      - gdash-network

  collector:
    build: ./collector-python
    container_name: weather-collector
    restart: unless-stopped
    environment:
      RABBITMQ_URL: ${RABBITMQ_URL}
    depends_on:
      - rabbitmq
    networks:
      - gdash-network

networks:
  gdash-network:
    driver: bridge
