version: "3.8"

services:
  mongodb:
    image: mongo:7.0
    container_name: weather-mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USERNAME:-admin}
      MONGO_INIT_ROOT_PASSWORD: ${MONGO_PASSWORD:-password}
      MONGO_INIT_DATABASE: ${MONGO_DBNAME:-weatherDB}
    volumes:
      - ./infra/data/mongo:/data/db
    networks:
      - gdash-network

  rabbitmq:
    image: rabbitmq:3-management
    container_name: weather-rabbitmq
    restart: unless-stopped
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER:-guest}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASSWORD:-guest}
    networks:
      - gdash-network

networks:
  gdash-network:
    driver: bridge
